Added new awesome person to describe cmd
ArmandBriere/Archy pull request #62
Opened 2022-09-06 21:21 UTC by opdelta

:)

2022-09-06 21:22 UTC, AlexandreLachanceGit commented
I don't approve. We have to stay accurate sorry.

2022-09-06 21:23 UTC, AlexandreLachanceGit requested changes
Put my id instead.

2022-09-06 21:23 UTC, ArmandBriere requested changes

2022-09-06 21:23 UTC, ArmandBriere commented on src/functions/describe/main.py
> +            if str(mentions[0]) == "135048445097410560" or str(mentions[0]) == "964693548396068916" or str(mentions[0]) == "127947460462116864":
Max line length is 120, run `tox`

2022-09-06 21:25 UTC, opdelta commented
> Put my id instead.

If I put yours and mine and you approve, we got a deal

2022-09-06 21:29 UTC, opdelta commented on src/functions/describe/main.py
> +            if str(mentions[0]) == "135048445097410560" or str(mentions[0]) == "964693548396068916" or str(mentions[0]) == "127947460462116864":
Changes made in latest commit :)

2022-09-14 16:08 UTC, ArmandBriere requested changes
Permission denied (Contact admin for more information)

2022-09-14 16:08 UTC, closed without merging