added i18next and translations
ArmandBriere/Archy pull request #83
Opened 2022-09-23 22:53 UTC by HeliumApple

Supported languages: English, French and Esperanto

2022-09-24 13:39 UTC, ArmandBriere requested changes
Je vais check le code ce matin et merge si ça fonctionne

2022-09-24 13:39 UTC, ArmandBriere commented on web/src/assets/locales/en.json
> +    "Leaderboard": {
On va écrire "leaderboard" en minuscule

2022-09-24 15:32 UTC, ArmandBriere commented on web/src/app/leaderboard/leaderboard.component.html
> -                {{ "Git gud" | uppercase }}
Ca me fait penser qu'il faut finir le setup du lint et prettier

2022-09-26 13:58 UTC, HeliumApple commented on web/src/assets/locales/en.json
> +    "Leaderboard": {
fixed

2022-10-01 21:31 UTC, ArmandBriere approved these changes

2022-10-01 21:33 UTC, merged